### ISSUE TITLE
A spec for maps closed for extension

### ISSUE THREAD

**Issue by lvh** [gfredericks/schpec#3]
clojure.spec/keys is open for extension, and its spec similarly generates keys not specified in the spec. Sometimes, you really just have a closed spec, for example, an existing third-party standard which doesn't allow extensions.

**Comment by lvh** [comment]
Suggested implementation:

``` clojure
(defmacro excl-keys
  "Like [[s/keys]], but closed for extension."
  [& {:keys [req-un opt-un req opt] :as keys-spec}]
  (let [bare-un-keys (map (comp keyword name) (concat req-un opt-un))
        all-keys (set (concat bare-un-keys req opt))]
    `(let [ks# (s/keys ~@(apply concat keys-spec))]
       (s/with-gen
         (s/and ks# (fn [m#] (set/subset? (set (keys m#)) ~all-keys)))
         (fn [] (gen/fmap (fn [m#] (select-keys m# ~all-keys)) (s/gen ks#)))))))
```

**Comment by lvh** [comment]
This should probably also take a way to opt-out of the extension. For example, JSON Schema allows extension but only with prefixed keys, so `"x-lvh-flavor"` or something.

**Comment by lvh** [comment]
I've added a feature to not add the check if a map really contains only these keys (in the spec), so that it only changes the generator. This can be important, because otherwise you can never merge these specs. clojure.spec tests that generated objects match all of the predicates from the merged specs, so if any of those predicates limits the keys to a small fixed set, the merged generator will never successfully produce any objects (unless you merge it with an empty, non-excl-keys, spec).

``` clojure
(defn limit-keys
  [spec-form ks]
  (let [ks (set ks)]
    (s/and spec-form (fn [m] (set/subset? (set (keys m)) ks)))))

(defmacro excl-keys
  "Like [[s/keys]], but closed for extension."
  [& {:keys [req-un opt-un req opt check-keys?]
      :as keys-spec
      :or {check-keys? true}}]
  (let [keys-spec (dissoc keys-spec :check-keys?)
        bare-un-keys (map (comp keyword name) (concat req-un opt-un))
        all-keys (set (concat bare-un-keys req opt))]
    `(let [ks# (s/keys ~@(apply concat keys-spec))]
       (s/with-gen
         (if ~check-keys?
           (limit-keys ks# ~all-keys)
           ks#)
         (fn [] (gen/fmap (fn [m#] (select-keys m# ~all-keys)) (s/gen ks#)))))))
```

**Comment by gfredericks** [comment]
When you say "you can never merge" are you talking about `clojure.spec/merge` in particular? Should we have an alternate implementation of `merge` that works on the closed specs?

**Comment by lvh** [comment]
Yes. I've "fixed" this by making the restriction optional and adding it as a separate fn (see #6). I can add a merge-excl if you want, but people still need to specify the non-checky bit when they make the original key specs, which I don't think I can fix unless I create my own Spec I guess?
